SELECT TBL_PBC_IF_IN_BPS.DATA_VAL, TBL_PBC_IF_IN_BPS.DEV_ID, TBL_PBC_IF_IN_BPS.DATA_VAL+3 AS val0 
FROM ( 
    SELECT TBL_PBC_IF_IN_BPS.DATA_VAL AS "TBL_PBC_IF_IN_BPS.DATA_VAL", 
            TBL_PBC_IF_IN_BPS.DEV_ID AS "TBL_PBC_IF_IN_BPS.DEV_ID" 
    FROM (SELECT DATA_VAL AS "DATA_VAL", DEV_ID AS "DEV_ID" 
            FROM TBL_PBC_IF_IN_BPS 
            WHERE ((1 = 1) AND (DEV_ID > 1) )AND ((1 = 1) AND (DEV_ID < 11) ) LIMIT 32) AS TBL_PBC_IF_IN_BPS   LIMIT 32
) t LIMIT 32


 SELECT  TBL_PBC_IF_IN_BPS.DATA_VAL ,  TBL_PBC_IF_IN_BPS.DEV_ID,  TBL_PBC_IF_IN_BPS.DATA_VAL+3 AS val_add_3 
 FROM ( SELECT TBL_PBC_IF_IN_BPS.DATA_VAL AS "TBL_PBC_IF_IN_BPS.DATA_VAL", 
                TBL_PBC_IF_IN_BPS.DEV_ID AS "TBL_PBC_IF_IN_BPS.DEV_ID" 
        FROM (SELECT DATA_VAL AS "DATA_VAL", DEV_ID AS "DEV_ID" FROM TBL_PBC_IF_IN_BPS WHERE ((1 = 1) AND (DEV_ID > 1) )AND ((1 = 1) AND (DEV_ID < 11) ) LIMIT 32) AS TBL_PBC_IF_IN_BPS   ) t LIMIT 32